export const INTERACTION_TYPES = ["CALL", "ONLINE_MEETING", "OFFLINE_MEETING"] as const;
export const STAKEHOLDER_TYPES = [
  "INFLUENCER",
  "DECISION_MAKER",
  "UNKNOWN",
] as const;
export const OUTCOMES = [
  "MET_INFLUENCER",
  "MET_DECISION_MAKER",
  "BUDGET_DISCUSSED",
  "DEMO_DONE",
  "PRICING_REQUESTED",
  "PROPOSAL_SHARED",
  "BUDGET_CONFIRMED",
  "NEGOTIATION_STARTED",
  "DEAL_CONFIRMED",
  "PO_RECEIVED",
  "NO_RESPONSE",
  "FOLLOW_UP_DONE",
  "INTERNAL_DISCUSSION",
  "DECISION_DELAYED",
  "DECISION_MAKER_UNAVAILABLE",
  "BUDGET_NOT_AVAILABLE",
  "DEAL_ON_HOLD",
  "LOST_TO_COMPETITOR",
  "DEAL_DROPPED",
] as const;
export const RISK_CATEGORIES = [
  "NO_ACCESS_TO_DM",
  "STUCK_WITH_INFLUENCER",
  "BUDGET_NOT_DISCUSSED",
  "BUDGET_NOT_CONFIRMED",
  "BUDGET_INSUFFICIENT",
  "COMPETITOR_INVOLVED",
  "COMPETITOR_PREFERRED",
  "DECISION_DELAYED",
  "LOW_PRODUCT_FIT",
  "FEATURE_GAP",
  "CHAMPION_NOT_STRONG",
  "INTERNAL_ALIGNMENT_MISSING",
] as const;

export type DealStage =
  | "ACCESS"
  | "QUALIFIED"
  | "EVALUATION"
  | "COMMITTED"
  | "CLOSED";
