export const STATE_ALIASES: Record<string, string> = {
  "andaman & nicobar islands": "Andaman and Nicobar Islands",
  "andaman nicobar islands": "Andaman and Nicobar Islands",
  "ap": "Andhra Pradesh",
  "ar": "Arunachal Pradesh",
  "as": "Assam",
  "br": "Bihar",
  "cg": "Chhattisgarh",
  "chattisgarh": "Chhattisgarh",
  "dadra and nagar haveli": "Dadra and Nagar Haveli and Daman and Diu",
  "dadra & nagar haveli": "Dadra and Nagar Haveli and Daman and Diu",
  "dadra & nagar haveli and daman & diu": "Dadra and Nagar Haveli and Daman and Diu",
  "daman and diu": "Dadra and Nagar Haveli and Daman and Diu",
  "dl": "Delhi",
  "gj": "Gujarat",
  "hp": "Himachal Pradesh",
  "hr": "Haryana",
  "jh": "Jharkhand",
  "jk": "Jammu and Kashmir",
  "j&k": "Jammu and Kashmir",
  "ka": "Karnataka",
  "kl": "Kerala",
  "la": "Ladakh",
  "ld": "Lakshadweep",
  "ml": "Meghalaya",
  "mn": "Manipur",
  "mh": "Maharashtra",
  "mp": "Madhya Pradesh",
  "mz": "Mizoram",
  "nl": "Nagaland",
  "od": "Odisha",
  "orissa": "Odisha",
  "pb": "Punjab",
  "py": "Puducherry",
  "rj": "Rajasthan",
  "tn": "Tamil Nadu",
  "ts": "Telangana",
  "tg": "Telangana",
  "uk": "Uttarakhand",
  "up": "Uttar Pradesh",
  "wb": "West Bengal",
};

export const DISTRICT_ALIASES: Record<string, string> = {
  "bangalore": "Bengaluru",
  "bangaluru": "Bengaluru",
  "bengaluru urban": "Bengaluru",
  "bombay": "Mumbai City",
  "gurugram": "Gurgaon",
  "mumbai": "Mumbai City",
  "new delhi": "Delhi",
};
